# Generated by Django 5.2.11 on 2026-02-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('headline', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, default='')),
                ('type', models.CharField(default='other', max_length=50)),
                ('polarity', models.IntegerField(default=0)),
                ('impact_score', models.IntegerField(default=0)),
                ('tags_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='EventsFetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('news_ok', models.BooleanField(default=False)),
                ('announcements_ok', models.BooleanField(default=False)),
                ('news_fetched', models.IntegerField(default=0)),
                ('announcements_fetched', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('sentiment', models.FloatField(default=0.0)),
                ('relevance', models.FloatField(default=1.0)),
                ('entities_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
