# Generated by Django 5.2.11 on 2026-02-11 10:43

from django.db import migrations, models


def dedupe_announcements(apps, schema_editor):
    Announcement = apps.get_model('events', 'Announcement')
    seen = set()
    duplicates = []
    for item in Announcement.objects.order_by('id').values('id', 'headline', 'published_at'):
        key = (item['headline'], item['published_at'])
        if key in seen:
            duplicates.append(item['id'])
        else:
            seen.add(key)
    if duplicates:
        Announcement.objects.filter(id__in=duplicates).delete()


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_announcements, noop),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.UniqueConstraint(fields=('headline', 'published_at'), name='uniq_announcement_headline_time'),
        ),
    ]