# Generated by Django 5.2.11 on 2026-02-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_announcement_uniq_announcement_headline_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='dedupe_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='low_priority',
            field=models.BooleanField(default=False),
        ),
    ]
