# Generated by Django 5.2.11 on 2026-02-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_announcement_dedupe_hash_announcement_low_priority'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.UniqueConstraint(fields=('dedupe_hash',), name='uniq_announcement_dedupe_hash'),
        ),
    ]
