# Generated by Django 5.2.11 on 2026-02-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_announcement_uniq_announcement_dedupe_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
