# Generated by Django 5.2.11 on 2026-02-11 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_announcement_dedupe_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='announcement',
            name='uniq_announcement_dedupe_hash',
        ),
    ]
