# Generated by Django 5.2.11 on 2026-02-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_dedupe_hash_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='announcement',
            name='uniq_announcement_headline_time',
        ),
    ]
