# Generated by Django 5.2.11 on 2026-02-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('provider_primary', models.CharField(max_length=50)),
                ('provider_fallback', models.CharField(max_length=50)),
                ('primary_ok', models.BooleanField(default=False)),
                ('fallback_ok', models.BooleanField(default=False)),
                ('candles_fetched_primary', models.IntegerField(default=0)),
                ('candles_fetched_fallback', models.IntegerField(default=0)),
                ('candles_saved', models.IntegerField(default=0)),
                ('missing_filled', models.IntegerField(default=0)),
                ('outliers_rejected', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
