# Generated by Django 5.2.11 on 2026-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature1m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, unique=True)),
                ('feature_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='SignalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, unique=True)),
                ('price_action_score', models.IntegerField(default=50)),
                ('volume_score', models.IntegerField(default=50)),
                ('news_score', models.IntegerField(default=50)),
                ('announcements_score', models.IntegerField(default=50)),
                ('regime_score', models.IntegerField(default=50)),
                ('overall_score', models.IntegerField(default=50)),
                ('explain_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
